spring.application.name=demo

server.port=8080

# Conexión a la base de datos (Asegúrate de que el nombre PPOOII sea igual al de pgAdmin)
spring.datasource.url=jdbc:postgresql://localhost:5432/lab02
spring.datasource.username=postgres
spring.datasource.password=1357924680
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraciones de JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public